import { test, expect } from "@playwright/test";

const backend = process.env.ROM_GALLERY_BACKEND_URL;
test("real ROM host authenticates, discovers semantic fields and persists a patch", async ({ page }, info) => {
  test.skip(!backend, "Requires the isolated ROM host and synthetic OIDC provider.");
  const base = new URL(backend!);
  expect(base.hostname).toBe("127.0.0.1");
  expect(base.protocol).toBe("http:");
  const runtimeErrors: string[] = [];
  page.on("pageerror", error => runtimeErrors.push(error.message));
  await page.goto(`${base.href}#rom`);
  await page.getByRole("link", { name: "Sign in with Local fixture", exact: true }).click();
  await page.getByLabel("Fixture account", { exact: true }).selectOption("bob");
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await page.getByRole("button", { name: "Allow", exact: true }).click();
  await expect(page).toHaveURL(base.href);
  await page.goto(`${base.href}#rom`);
  await page.getByLabel("Resource kind", { exact: true }).selectOption("field-showcase");
  await page.getByRole("button", { name: "workshop-sample", exact: true }).click();
  await page.getByRole("button", { name: "Choose Related task reference", exact: true }).click();
  await page.getByRole("option", { name: /Review report/ }).click();
  await expect(page.getByText("Review report", { exact: true })).toBeVisible();
  const name = page.getByRole("textbox", { name: "Name value", exact: true });
  const saved = `ROM gallery ${info.project.name} ${Date.now()}`;
  await name.fill(saved);
  await expect(page.getByText("Review report", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Save 2 changes", exact: true }).click();
  await expect(name).toHaveValue(saved);
  await expect(page.getByRole("button", { name: "Save changes", exact: true })).toBeDisabled();
  await page.reload();
  await page.getByLabel("Resource kind", { exact: true }).selectOption("field-showcase");
  await page.getByRole("button", { name: "workshop-sample", exact: true }).click();
  await expect(name).toHaveValue(saved);
  await expect(page.getByRole("textbox", { name: "decimal value", exact: true })).toHaveValue("12345678901234567890.123456789");
  await expect(page.getByRole("heading", { name: "Live ROM Resources", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Choose Related task reference", exact: true }).click();
  await page.getByRole("option", { name: /Review report/ }).click();
  await expect(page.getByText("Review report", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await expect(page.getByText("Session: anonymous", { exact: true })).toBeVisible();
  await expect(page.getByText("Review report", { exact: true })).toHaveCount(0);
  await expect(name).toHaveCount(0);
  expect(runtimeErrors).toEqual([]);
});
